# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: AGENT Challenge
short_description: Challenge for Core Psychological Reasoning Tasks
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.png
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Leaderboard for the AGENT challenge
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2022-08-20 00:00:00
end_date: 2023-12-31 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Scenario 1", "Scenario 2", "Scenario 3", "Scenario 4", "All"],
        "default_order_by": "All",
        "metadata": {
          "Scenario 1": {
            "sort_ascending": True,
            "description": "Accuracy for trials in Scenario 1",
          },
          "Scenario 2": {
            "sort_ascending": True,
            "description": "Accuracy for trials in Scenario 2",
          },
          "Scenario 3": {
            "sort_ascending": True,
            "description": "Accuracy for trials in Scenario 3",
          },
          "Scenario 4": {
            "sort_ascending": True,
            "description": "Accuracy for trials in Scenario 4",
          },
          "All": {
            "sort_ascending": True,
            "description": "Accuracy for all trials",
          }
        }
      }

challenge_phases:
    - id: 1
      name: Test Phase
      description: templates/challenge_phase_1_description.html
      leaderboard_public: True
      is_public: True
      is_submission_public: True
      start_date: 2022-06-20 00:00:00
      end_date: 2023-12-31 23:59:59
      test_annotation_file: annotations/test_annotations_testsplit.json
      codename: test
      max_submissions_per_day: 5
      max_submissions_per_month: 50
      max_submissions: 50
      default_submission_meta_attributes:
        - name: method_name
          is_visible: True
        - name: method_description
          is_visible: True
        - name: project_url
          is_visible: True
        - name: publication_url
          is_visible: True
      submission_meta_attributes:
        - name: MultipleChoiceAttribute
          description: Types of input used by the model
          type: checkbox
          options: ["RGB", "Depth", "Segmentation", "State"]
      is_restricted_to_select_one_submission: False
      is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
